language: python
python:
- '2.7'
- '3.8'
install:
- pip install -r tests/requirements.txt
- pip install coveralls
script:
- coverage run tests/test_case.py
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kwkw
  password:
    secure: mACGXSn0n+ZN3U5AEndajwA4pWvLB9eU1FrVlNs7yIdz7C+Je8HmXoEUj3FFHase6poQpypMBSKTiKTQbeeacKCRIw2su+CwcqlAqyKsqxbr+aRgMn1f9SDWtiBc7OsKdS/DgUSrQ3rftC1vR2TN4mbar72SaEbKRjB5MP+eicA/haPcauGR/d9qqJxDIriPhV272CY2umS6oPiucYDTqp5VdVL7vGZjzzyZXs60fNqZhvalyTt45fEAEWAaAusfj/D257DvGAvk/5x/RiPdrr5hYXYz9liGdjfQGs7BN6juajX1do0QJfHSgmgws4kRVCb3jTuoo6zmfXdlVAazpur6msdDEo1Nls97fPShtJvTfil95mQ3r41YxRnYlEHt/ZvABaBMg2dv6gpFMiXVtsms8ZgIoSzypdojz2l4/LqkpgTO6XNlz6GpHkHK54HBcjPrhxMuyRGYIOpDpD9n/g58YV8SAADWAFSAeCDXM6HNdpbQEO9q9DoGyUCh3mGxeTCV75X/lD0+SDNxoJvJSaZg9YcvhqHkxCFAuxMOrTjkCrT6IbYG1Hj+bmZv7wRtZV9MbNIYwMy2bn4GkLEiMA+3xaHkIRxBVMDV10lGunFrUs/CG0PQOrIJG+HQm9ps/45uXC51LPzd1HViwdP0dAZzt+50D6fRKEVBSZIdsTo=
  on:
    tags: true
    branch: master
after_success: coveralls
